alias ls='ls -G'
alias tmux='tmux -2'
alias gcd='cd ./$(git rev-parse --show-cdup)'
alias go='open https://`ghq list | peco`'
alias gs='git status --short'
alias ts='tig status'
alias gl='git log --graph'
alias gd='git difftool'
alias gdc='git difftool --cached'
alias gdh='git difftool HEAD'
alias vim='nvim'
alias mvim='open -a MacVim "$@"'
alias decode_unicode_encode='sed -e "s/\\u\(....\)/\&#x\1;/g" | nkf --numchar-input'

# change tmux prefix for ssh
alias tmux-changekey='tmux set-option -ag prefix C-b'
alias tmux-revertkey='tmux set-option -ag prefix C-t'
